### ISSUE TITLE
Detect and embed FurAffinity submission links in comments

### ISSUE THREAD

**Issue by CopperBadger** [CopperBadger/fastyle#40]

**Comment by CopperBadger** [comment]
Going to hold off on this one, it could introduce undue server load if the feature triggers automatically.

**Comment by rubi-t8** [comment]
Could do it lazy load style. Essentially once you scroll to it, load the
thumbnail.

**Comment by CopperBadger** [comment]
That would be better for the servers however it may result in jumping page content if the user scrolls past a bunch of linked images. I was thinking we could put a little "(Show)" button after each link

**Comment by rubi-t8** [comment]
Could we possibly do a Bootstrap popover preview? Grab it with AJAX when the user clicks the link. Sort of like [this](http://www.bootply.com/LOxKpfJ0uY) (click on the red text, positioning acting a little funny).

**Comment by CopperBadger** [comment]
Oh yeah, definitely-- that would be even better ^^

**Comment by rubi-t8** [comment]
I may go ahead and do this then. Just busy during the week because college. May at least write the AJAX request tonight.
