### ISSUE TITLE
Convert: Commission Information

### ISSUE THREAD

**Issue by CopperBadger** [CopperBadger/fastyle#41]

**Comment by rubi-t8** [comment]
Almost have this done, just trying to make the images match the other thumbnail styling.
![cominfo](https://cloud.githubusercontent.com/assets/2555575/5888526/40647e3c-a3d0-11e4-964b-271570a850f3.png)

**Comment by CopperBadger** [comment]
Looks awesome! I've been using the `img-rounded` class for most all of the thumbnails on the site, manually setting the width so they look nice and uniform-- I can take care of that if you'd like

**Comment by rubi-t8** [comment]
I figured it out looking at the existing code. Just need to grab the username and then I'm going to commit the changes.

Have a monkey! :monkey:

**Comment by CopperBadger** [comment]
Awwr thanks :3 Super!
