### ISSUE TITLE
Use check_username service to display if a search query matches a username

### ISSUE THREAD

**Issue by CopperBadger** [CopperBadger/fastyle#45]
Eg, user searches for "thanshuhai", the search page would send an AJAX request to `/register/?phase=5&mode=check_username` with the string as the `username` parameter. If the status in the returned JSON object is 1, then that user exists! And we should display a link leading to that user's page at the top of the search results. AJAX shouldn't be sent if the string isn't a valid username. According to the server, "only letters and numbers, dash, underscore, tilde and a dot are allowed" (ie, `/^[A-Za-z0-9-_~\.]+$/`) in usernames. They must also contain at least three alphanumeric characters.

**Comment by rubi-t8** [comment]
So basically, if a user searches for a username it would bring you to their Profile/gallery?

**Comment by CopperBadger** [comment]
It should display a prominent link at the top of the search results with the searched-for user's avatar and name in nice big letters, with a smaller title above the name that says "Username match!" or something. I would use a `list-group` containing a single link, so that the whole header would be clickable. That way the user would have the option to go to that artist's profile, or just browse the results that match their name.

**Comment by rubi-t8** [comment]
Okay, cool. I'm working on this then.

**Comment by CopperBadger** [comment]
Ookie ^^ have a look at `register.js` for the AJAX call

**Comment by rubi-t8** [comment]
Done! I also added in a line to show what you searched for

![2015-01-25_1542](https://cloud.githubusercontent.com/assets/2555575/5893198/bed1cd00-a4a8-11e4-9d64-09e09d32588d.png)

**Comment by CopperBadger** [comment]
Oh, that looks awesome! :D

**Comment by rubi-t8** [comment]
Thanks! I like how it turned out. I did, however, realize I forgot to check that the search is at least three alphanumeric characters. You think it's worth putting it in or not?

**Comment by CopperBadger** [comment]
Yeah, we probably should to minimize server requests. Also, the search header is displayed on the search form page, could you have it `.hide()` if there is no search term?

**Comment by rubi-t8** [comment]
Oh whoops, overlooked showing that `div` when you first open the page. And I'll work on adding that check to further reduce the server calls.

**Comment by rubi-t8** [comment]
And, fixed!
