### ISSUE TITLE
Infinity scroll not working correctly (/browse, /msg/submissions/)

### ISSUE THREAD

**Issue by skulblakka** [CopperBadger/fastyle#47]
The first time I reach the end of a site it triggers correctly and loads the next set of images but afterwards it does nothing. But if I resize the windows it does trigger again once. Afterwards I need to resize the window again. 

This happens on /browse and /msg/submissions/ but works fine on /search and a user's gallery.

**Comment by skulblakka** [comment]
Also it does not work on journals at all but I'm not sure if it just hasn't been added yet.

**Comment by CopperBadger** [comment]
I've added in a manual load button that you can press in case the loading isn't triggered automatically by scrolling-- doesn't fix the core issue, but provides a good fail-safe. Changes have been pushed to the repo, feel free to check them out

**Comment by skulblakka** [comment]
Now it just says "No more images to load!" after the first time its being triggered. If I try to resize the window like I did before it says 

> resizing window...
> Setting scroll thresh = 6338, doc height = 7580 
> Failed to reinitiate: ctl=false, thresh=0

in console and nothing happens.

**Comment by CopperBadger** [comment]
Hmm that's puzzling :T It's working on both browsers on my machine. Does that happen on all of the galleries or just on a particular page(s)? Also, which browser and browser version are you using?

I've tried a couple of extra things that may be causing the issue, they've been committed to the repo.

**Comment by skulblakka** [comment]
It worked on galleries the whole time. The issue appeared on /browse and submission messages but your latest changes fixed it. Works on all pages I tested.

**Comment by CopperBadger** [comment]
Excellent! I'm interested in finding out why it wasn't working before-- if you could tell me your browser and version I'd love to use it for future compatibility testing

**Comment by skulblakka** [comment]
I'm using Google Chrome Version 40.0.2214.91 m (64-bit) on Windows 8.1

**Comment by CopperBadger** [comment]
Super-- thanks! I've been using Chromium 39, might explain some of the issues
