### ISSUE TITLE
Idea: Add arrow key functionality to submission pages to browse a user's gallery

### ISSUE THREAD

**Issue by rubi-t8** [CopperBadger/fastyle#64]
~~like [KeyAffinity](http://github.com/therealgitcub/keyaffinity)!~~

No really though, could be a welcome feature. Possibly some other shortcuts but nothing like I did with KA. I didn't choose those combinations very well.

**Comment by CopperBadger** [comment]
I added this in one of the latest commits actually :)

**Comment by rubi-t8** [comment]
Haha, didn't think to actually check if it was in there... :P
