### ISSUE TITLE
My FA Menu clips screen

### ISSUE THREAD

**Issue by PolarisBeaver** [CopperBadger/fastyle#75]
The current menu looks fantastic (I like how the options are all expanded), however in its current state it is a tad too long, and goes out of the screen! http://i.imgur.com/cbrWNT1.jpg

A couple options to consider, try adjusting the top and bottom padding/margins/border/whatever, or perhaps even a scroll bar.

If all else fails, try having each submenu be an expandable list, all collapsed by default but when you click it, the child links expand inline exactly the way they look now. If you want a better idea of what I mean, imagine the current menu looks as if a user expanded every submenu. For this, have a + icon within a square to signify that the submenu is expandable, and when it's clicked it turns into a - icon within a square.

**Comment by CopperBadger** [comment]
Thanks for reporting this Polaris ^^ I would like to have the dropdown redesigned anyway-- the way it is right now was sort of a temporary fix. Using nested menus would probably be the best solution, though bootstrap doesn't seem to support them natively. Once I implement #77 (should be in a few moments), the issue will be avoidable by using a static header, but this will definitely be taken care of.

**Comment by rubi-t8** [comment]
Didn't realize Bootstrap doesn't support nested menus

I should be able to do a little bit of jQuery magic to make the menu scrollable if your window size doesn't fit the entire bar. I was able to get it looking like this with the inspector panel. 

![2015-02-09_1401](https://cloud.githubusercontent.com/assets/2555575/6113308/740d0a4c-b064-11e4-95b9-5a56de4a7fa2.png)

**Comment by PolarisBeaver** [comment]
That looks pretty good, and all it needs is a scroll bar so any new users would know their menu is scrollable. Or perhaps an arrow at the bottom of the menu that when you hover or click it, it will scroll the list?

**Comment by rubi-t8** [comment]
It would have your system default scroll bar, yes. I'm on a Mac using a
touch mouse, so the bar is hidden in the screenshot.
