### ISSUE TITLE
User icon cut off by menu on submission page

### ISSUE THREAD

**Issue by skulblakka** [CopperBadger/fastyle#76]
The user icon is cut off by the menu bar on submission pages (see http://i.imgur.com/sQfrfKm.jpg) (just noticed it also happens on other pages, e.g. the buttons on to of the submission message page)

There is also a preview button that displays the current submission you are viewing (see http://i.imgur.com/dF14mKW.jpg)

**Comment by PolarisBeaver** [comment]
I can confirm this is happening to me too, with the "remove" and "nuke" buttons being pushed up top.
I think it's happening for other elements too on other pages.

![untitled](https://cloud.githubusercontent.com/assets/10394552/6089897/3dc0dfc8-ae1f-11e4-8c2e-5ad9133de001.png)

**Comment by CopperBadger** [comment]
Ahh thanks for reporting this-- it was fixed on my local workspace but I forgot to push one of the scripts ><
